### ISSUE TITLE
Failed test GithubTicketFetcherIntegTest

### ISSUE THREAD

**Issue by slawekjaranowski** [shipkit/shipkit-changelog#83]
I have:
```
Problems fetching 3 tickets from Github
java.lang.RuntimeException: Problems fetching 3 tickets from Github
	at org.shipkit.changelog.GithubTicketFetcher.fetchTickets(GithubTicketFetcher.java:40)
	at org.shipkit.changelog.GithubTicketFetcherIntegTest.fetches from Github(GithubTicketFetcherIntegTest.groovy:13)
Caused by: java.io.IOException: GET https://api.github.com/repos/mockito/mockito/issues?page=1&per_page=100&state=closed&filter=all&direction=desc failed, response code = 401, response body:
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
	at org.shipkit.changelog.GithubApi.call(GithubApi.java:86)
```

```
org.shipkit.changelog.GithubTicketFetcherIntegTest > fetches from Github FAILED
    java.lang.RuntimeException at GithubTicketFetcherIntegTest.groovy:13
        Caused by: java.io.IOException at GithubTicketFetcherIntegTest.groovy:13
```

Probably token used in test was removed.

**Comment by mockitoguy** [comment]
Let's `@Ignore` those tests and document that they are handy tests to temporarily unignore for local dev/debugging.

Let's replace the token with something like "TODO-put-your-own-token-here" :)

Sounds OK?
