### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by ianbondoc** [shipkit/shipkit-changelog#90]
Hi, is it possible to use this for private repos?  Got this when i tried generateChangeLog and got this:

Caused by: java.io.IOException: GET https://api.github.com/repos/my/private/repository/issues?page=1&per_page=100&state=closed&filter=all&direction=desc failed, response code = 404, response body:
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/issues#list-repository-issues"}
        at org.shipkit.changelog.GithubApi.call(GithubApi.java:86)
        at org.shipkit.changelog.GithubApi.doRequest(GithubApi.java:66)
        at org.shipkit.changelog.GithubApi.get(GithubApi.java:35)
        at org.shipkit.changelog.GithubListFetcher.nextPage(GitHubListFetcher.java:46)
        at org.shipkit.changelog.GithubTicketFetcher.fetchTickets(GithubTicketFetcher.java:33)

**Comment by mockitoguy** [comment]
Sure! You can configure `githubUrl`, see example in "Usage" section of the readme: https://github.com/shipkit/shipkit-changelog#usage

**Comment by mockitoguy** [comment]
Sorry, I did not notice this issue opened earlier.

**Comment by ianbondoc** [comment]
thanks! will try that but for now ended up building the same functionality for our project

**Comment by mockitoguy** [comment]
Sounds good and good luck!
